### PR TITLE
Fix object comparison for default value in ObjectParameter constructor

### PR DESCRIPTION
**Pull request by jkbelcher**

### CODE REVIEW

**Review by mcslee — CHANGES_REQUESTED** [review]
Sorry just realized to be fully safe here, we should check for two nulls. It's obviously a terrible idea to put nulls in here, but also a bad idea to `NullPointerException` if someone does.

**Comment by mcslee** [comment]
Fixed here: https://github.com/heronarts/LX/commit/4edf4ecd18c110e2e590b679c3626b1b35bc7d67

**Comment by jkbelcher** [comment]
So `value` is not null as checked by the preceding lines.  I was only thinking of the immediate use case of Strings, where string.equals(null) should return false.  Are you concerned some object will throw an exception on .equals(null)?

**Comment by mcslee** [comment]
Oh good point forgot null is checked above. In any case Objects.equals that
I pushed in there will be fine

Le sam. 17 juin 2023 à 06:01, Justin Belcher ***@***.***> a
écrit :

**Pull request closed without merging**
