### PR TITLE
Improve disposal of listeners from APC40mkII and MFT midi controllers

### PR DESCRIPTION
**Pull request by jkbelcher**
This cleans up the last errors regarding stranded listeners on program exit and on midi controller enable->disable->enable cycle.  Could use your review to see if this was done properly.

### CODE REVIEW

**Comment by jkbelcher** [comment]
Oops selected the master branch as base by accident.  Changed the merge target to dev branch.  This is a branch from the mft pull request.

**Comment by mcslee** [comment]
Nice one - just very minor comments here.

**Comment by mcslee** [comment]
FYI - think you'l need to resolve some conflicts here as the added commit went on the first pull request. Sorry I didn't reailze this until after merging. I think this shouldn't be too awkward to merge though.

**Comment by jkbelcher** [comment]
No problem, was planning to delete and re-do this commit since I already moved half of it to the other one.

**Pull request closed without merging**
